# Generated by Django 2.2.5 on 2022-11-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='adtitle')),
                ('link', models.CharField(max_length=500, verbose_name='adlinks')),
                ('image_url', models.CharField(max_length=255, verbose_name='picture')),
                ('remark', models.TextField(verbose_name='tips')),
                ('is_show', models.BooleanField(default=False, verbose_name='show or not show')),
                ('orders', models.IntegerField(default=1, verbose_name='sort')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete or not delete')),
            ],
            options={
                'verbose_name': '轮播广告',
                'verbose_name_plural': '轮播广告',
                'db_table': 'p_educate_banner',
            },
        ),
    ]
